project_id = "rgikflkocotkljbajzrb"

[functions]
  [functions.admin-db-maintenance]
    verify_jwt = false
  [functions.admin-manage-users]
    verify_jwt = false
  [functions.approve-referral-reward]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.auto-suspend]
    verify_jwt = false
  [functions.check-username]
    verify_jwt = false
  [functions.create-employee]
    verify_jwt = false
  [functions.customer-vault]
    verify_jwt = false
  [functions.demo-login]
    verify_jwt = false
  [functions.demo-provision]
    verify_jwt = false
  [functions.generate-closing-report]
    verify_jwt = false
  [functions.math-challenge]
    verify_jwt = false
  [functions.notify-admin-signup]
    verify_jwt = false
  [functions.notify-subscription-bonus]
    verify_jwt = false
  [functions.notify-waitlist]
    verify_jwt = false
  [functions.optimize-logo]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-notification-email]
    verify_jwt = false
  [functions.send-onboarding-reminder]
    verify_jwt = false
  [functions.send-password-reset]
    verify_jwt = false
  [functions.send-verification-reminder]
    verify_jwt = false
  [functions.send-web-push]
    verify_jwt = false
  [functions.signup-guard]
    verify_jwt = false
  [functions.subscription-expiry-reminder]
    verify_jwt = false
  [functions.system-health-monitor]
    verify_jwt = false
  [functions.wipe-employee]
    verify_jwt = false