project_id = "rgikflkocotkljbajzrb"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.notify-admin-signup]
    verify_jwt = false
  [functions.send-web-push]
    verify_jwt = false
