// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-repairs.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_repairs_default = defineTool({
  name: "list_repairs",
  title: "List repairs",
  description: "List repair tickets for the signed-in shop, optionally filtered by status. Returns ticket number, device, status, costs and customer.",
  inputSchema: {
    status: z.enum(["pending", "in_progress", "completed", "delivered", "rejected"]).optional().describe("Optional repair status filter."),
    limit: z.number().int().min(1).max(100).optional().describe("Max number of repairs to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser(ctx).from("repairs").select(
      "id, ticket_number, status, device_model, problem_description, total_cost, amount_paid, deposit_date, delivery_date, customer:customers(name, phone)"
    ).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { repairs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-inventory.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_inventory_default = defineTool2({
  name: "search_inventory",
  title: "Search inventory",
  description: "Search the shop's product inventory by name, SKU or barcode. Returns matching products with stock quantity and prices.",
  inputSchema: {
    query: z2.string().trim().optional().describe("Text to match against product name or SKU. Omit to list recent products."),
    low_stock_only: z2.boolean().optional().describe("When true, only return products at or below their minimum stock level."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max number of products to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, low_stock_only, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser2(ctx).from("products").select(
      "id, name, sku, quantity, min_quantity, cost_price, sell_price, category:categories(name)"
    ).order("name").limit(limit ?? 25);
    if (query && query.length > 0) {
      q = q.or(`name.ilike.%${query}%,sku.ilike.%${query}%`);
    }
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    let rows = data ?? [];
    if (low_stock_only) {
      rows = rows.filter(
        (p) => Number(p.quantity) <= Number(p.min_quantity ?? 0)
      );
    }
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { products: rows }
    };
  }
});

// src/lib/mcp/tools/search-customers.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_customers_default = defineTool3({
  name: "search_customers",
  title: "Search customers",
  description: "Find customers of the signed-in shop by name, phone or email. Returns contact details, balance and loyalty points.",
  inputSchema: {
    query: z3.string().trim().optional().describe("Text to match against customer name, phone or email. Omit to list recent customers."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max number of customers to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser3(ctx).from("customers").select("id, name, phone, email, balance, loyalty_points, created_at").order("name").limit(limit ?? 25);
    if (query && query.length > 0) {
      q = q.or(`name.ilike.%${query}%,phone.ilike.%${query}%,email.ilike.%${query}%`);
    }
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { customers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-shop-overview.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_shop_overview_default = defineTool4({
  name: "get_shop_overview",
  title: "Get shop overview",
  description: "Get a quick overview of the signed-in shop: number of customers, products, and repairs pending vs in progress.",
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser4(ctx);
    const [customers, products, pending, inProgress] = await Promise.all([
      sb.from("customers").select("id", { count: "exact", head: true }),
      sb.from("products").select("id", { count: "exact", head: true }),
      sb.from("repairs").select("id", { count: "exact", head: true }).eq("status", "pending"),
      sb.from("repairs").select("id", { count: "exact", head: true }).eq("status", "in_progress")
    ]);
    const firstError = customers.error || products.error || pending.error || inProgress.error;
    if (firstError)
      return { content: [{ type: "text", text: firstError.message }], isError: true };
    const overview = {
      customers: customers.count ?? 0,
      products: products.count ?? 0,
      repairs_pending: pending.count ?? 0,
      repairs_in_progress: inProgress.count ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(overview, null, 2) }],
      structuredContent: { overview }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rgikflkocotkljbajzrb";
var mcp_default = defineMcp({
  name: "atelier-pro-mcp",
  title: "Atelier Pro MCP",
  version: "0.1.0",
  instructions: "Tools for a phone repair shop management app. Use `get_shop_overview` for a summary, `list_repairs` to browse repair tickets, `search_inventory` for products/stock, and `search_customers` to look up customers. All tools act as the signed-in shop owner.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_shop_overview_default,
    list_repairs_default,
    search_inventory_default,
    search_customers_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
