import { createClient } from 'npm:@supabase/supabase-js@2'
import { corsHeaders } from 'npm:@supabase/supabase-js@2/cors'

// Public endpoint (no auth): triggered by the "forgot password" form.
// Always returns { ok: true } to avoid username / account enumeration.
//
// Security model:
//  - The e-mail never contains a password. It carries a single-use, 1h
//    recovery link generated by the auth server.
//  - A missing profile e-mail can be supplied by the requester, but it is only
//    stored (and used) when the phone number they provide matches the phone we
//    already hold for that account. Otherwise nothing is sent.
//  - Throttled per username (3/h) and per IP (5/h).

const MAX_PER_USERNAME_PER_HOUR = 3
const MAX_PER_IP_PER_HOUR = 5
const DEFAULT_ORIGIN = 'https://repairpro-tunisia.com'

const digits = (v: string) => v.replace(/[^0-9]/g, '')

function phoneMatches(candidate: string, ...known: (string | null | undefined)[]) {
  const c = digits(candidate)
  if (c.length < 6) return false
  return known.some((k) => {
    const d = digits(String(k ?? ''))
    return d.length >= 6 && (d.endsWith(c) || c.endsWith(d))
  })
}

function isSafeOrigin(candidate: string, configuredDomain?: string | null): boolean {
  if (!candidate || typeof candidate !== 'string') return false
  try {
    const url = new URL(candidate)
    const host = url.hostname.toLowerCase()
    
    // Local development
    if (host === 'localhost' || host === '127.0.0.1') return true
    
    // Lovable preview / staging domains
    if (
      host.endsWith('.lovable.app') ||
      host.endsWith('.lovableproject.com') ||
      host.endsWith('.lovable.dev') ||
      host.endsWith('.gpt-eng.com') ||
      host.endsWith('.gptengineer.run')
    ) {
      return true
    }
    
    // Production brand domains
    if (host === 'repairpro-tunisia.com' || host.endsWith('.repairpro-tunisia.com')) {
      return true
    }
    
    // Custom configured domain from platform_settings
    if (configuredDomain) {
      const configuredHost = new URL(
        configuredDomain.startsWith('http') ? configuredDomain : `https://${configuredDomain}`
      ).hostname.toLowerCase()
      if (host === configuredHost || host.endsWith(`.${configuredHost}`)) {
        return true
      }
    }
    
    return false
  } catch {
    return false
  }
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  const ok = () =>
    new Response(JSON.stringify({ ok: true }), {
      status: 200,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!
    const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    const admin = createClient(supabaseUrl, serviceKey)

    const body = (await req.json().catch(() => ({}))) as {
      username?: string
      identifier?: string
      email?: string
      phone?: string
      origin?: string
      redirectTo?: string
    }

    const rawIdentifier = String(body.identifier || body.username || '').trim().toLowerCase()
    const providedEmail = String(body.email ?? '').trim().toLowerCase()
    const providedPhone = String(body.phone ?? '').trim()
    if (!rawIdentifier && !providedEmail) return ok()

    const searchIdentifier = rawIdentifier || providedEmail

    const ip =
      req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ||
      req.headers.get('cf-connecting-ip') ||
      req.headers.get('x-real-ip') ||
      'unknown'

    const oneHourAgo = new Date(Date.now() - 60 * 60 * 1000).toISOString()

    // ── Throttling ────────────────────────────────────────────────────────
    const [byUser, byIp] = await Promise.all([
      admin
        .from('password_reset_attempts')
        .select('id', { count: 'exact', head: true })
        .eq('username', searchIdentifier)
        .gte('created_at', oneHourAgo),
      admin
        .from('password_reset_attempts')
        .select('id', { count: 'exact', head: true })
        .eq('ip_address', ip)
        .gte('created_at', oneHourAgo),
    ])

    if ((byUser.count ?? 0) >= MAX_PER_USERNAME_PER_HOUR) return ok()
    if ((byIp.count ?? 0) >= MAX_PER_IP_PER_HOUR) return ok()

    await admin.from('password_reset_attempts').insert({ username: searchIdentifier, ip_address: ip })

    // Housekeeping: drop rows older than 24h (fire and forget).
    const oneDayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString()
    admin.from('password_reset_attempts').delete().lt('created_at', oneDayAgo).then(() => {})

    // ── Resolve the account ───────────────────────────────────────────────
    let profileQuery = admin
      .from('profiles')
      .select('user_id, username, email, phone, whatsapp_phone')

    if (searchIdentifier.includes('@')) {
      profileQuery = profileQuery.or(`email.ilike.${searchIdentifier},username.ilike.${searchIdentifier}`)
    } else {
      profileQuery = profileQuery.ilike('username', searchIdentifier)
    }

    const { data: profile } = await profileQuery.maybeSingle()

    if (!profile?.user_id) return ok()

    const { data: userRes } = await admin.auth.admin.getUserById(profile.user_id)
    const authEmail = userRes.user?.email
    if (!authEmail) return ok()

    const isRealEmail = (v?: string | null) =>
      !!v && v.includes('@') && !v.toLowerCase().endsWith('@repairpro.local')

    let targetEmail = isRealEmail(profile.email) ? String(profile.email).trim() : null

    // No e-mail on file: accept the one supplied, but only after the phone
    // number proves the requester already knows the account's contact details.
    if (!targetEmail && isRealEmail(providedEmail)) {
      const { data: shop } = await admin
        .from('shop_settings')
        .select('phone, whatsapp_phone')
        .eq('user_id', profile.user_id)
        .maybeSingle()

      const matched =
        !!providedPhone &&
        phoneMatches(
          providedPhone,
          profile.phone,
          profile.whatsapp_phone,
          shop?.phone,
          shop?.whatsapp_phone,
        )

      if (matched) {
        targetEmail = providedEmail
        await admin.from('profiles').update({ email: providedEmail }).eq('user_id', profile.user_id)
      }
    }

    // A supplied e-mail must equal the stored one; we never redirect a reset
    // link to an address the account does not own.
    if (
      targetEmail &&
      isRealEmail(providedEmail) &&
      providedEmail !== targetEmail.toLowerCase()
    ) {
      return ok()
    }

    if (!targetEmail) return ok()

    // ── Resolve redirect URL / origin safely ──────────────────────────────
    const { data: settingRow } = await admin
      .from('platform_settings')
      .select('value')
      .eq('key', 'public_site_domain')
      .maybeSingle()
    const configuredDomain = settingRow?.value?.trim() || ''

    const requestOrigin =
      body.origin ||
      req.headers.get('origin') ||
      (req.headers.get('referer') ? new URL(req.headers.get('referer')!).origin : null) ||
      Deno.env.get('APP_URL')

    let resolvedOrigin = DEFAULT_ORIGIN
    if (requestOrigin && isSafeOrigin(requestOrigin, configuredDomain)) {
      resolvedOrigin = requestOrigin.replace(/\/+$/, '')
    } else if (configuredDomain && isSafeOrigin(configuredDomain, configuredDomain)) {
      resolvedOrigin = (configuredDomain.startsWith('http') ? configuredDomain : `https://${configuredDomain}`).replace(/\/+$/, '')
    }

    const redirectTo = `${resolvedOrigin}/update-password`

    const { data: linkData, error: linkError } = await admin.auth.admin.generateLink({
      type: 'recovery',
      email: authEmail,
      options: { redirectTo },
    })
    if (linkError || !linkData?.properties?.action_link) {
      console.error('[send-password-reset] generateLink error', linkError)
      return ok()
    }

    const resp = await fetch(`${supabaseUrl}/functions/v1/send-notification-email`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${serviceKey}`,
        apikey: serviceKey,
      },
      body: JSON.stringify({
        action: 'send',
        template_key: 'password_reset',
        to: targetEmail,
        variables: {
          reset_url: linkData.properties.action_link,
          expiry_hours: 1,
        },
      }),
    })
    if (!resp.ok) {
      console.error('[send-password-reset] send failed', resp.status, await resp.text())
    }

    return ok()
  } catch (e) {
    console.error('[send-password-reset] error', e)
    return ok()
  }
})
